# Generated by Django 4.0.1 on 2022-01-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_animal_viewing_price_alter_animal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='viewing_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
